spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/subscriptionschema
    password: password123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: 'true'

aws:
  endpointUrl: https://new-stack-tv-dev.s3.sa-east-1.amazonaws.com
  region: sa-east-1
  bucketName: new-stack-tv-dev
  key: ASIA3GNKGV5722ACCRF7
  secret: n9+01DwM4TZL/hvJUFyj0TNPwvGLXOuQEUSziI1g